import { Dumbbell, Shield, Target, Zap } from "lucide-react";

export const LESSON_TYPE_CONFIG = {
  pitching: {
    icon: Target,
    label: "Pitching",
    accentBg: "bg-emerald-500",
    accentBorder: "border-l-emerald-500",
    badgeBg: "bg-emerald-100 dark:bg-emerald-900/40",
    badgeText: "text-emerald-700 dark:text-emerald-300",
    badgeBorder: "border-emerald-300 dark:border-emerald-700",
    iconBg: "bg-emerald-100 dark:bg-emerald-900/40",
    iconText: "text-emerald-600 dark:text-emerald-400",
  },
  hitting: {
    icon: Zap,
    label: "Hitting",
    accentBg: "bg-amber-500",
    accentBorder: "border-l-amber-500",
    badgeBg: "bg-amber-100 dark:bg-amber-900/40",
    badgeText: "text-amber-700 dark:text-amber-300",
    badgeBorder: "border-amber-300 dark:border-amber-700",
    iconBg: "bg-amber-100 dark:bg-amber-900/40",
    iconText: "text-amber-600 dark:text-amber-400",
  },
  fielding: {
    icon: Shield,
    label: "Fielding",
    accentBg: "bg-sky-500",
    accentBorder: "border-l-sky-500",
    badgeBg: "bg-sky-100 dark:bg-sky-900/40",
    badgeText: "text-sky-700 dark:text-sky-300",
    badgeBorder: "border-sky-300 dark:border-sky-700",
    iconBg: "bg-sky-100 dark:bg-sky-900/40",
    iconText: "text-sky-600 dark:text-sky-400",
  },
  catching: {
    icon: Target,
    label: "Catching",
    accentBg: "bg-violet-500",
    accentBorder: "border-l-violet-500",
    badgeBg: "bg-violet-100 dark:bg-violet-900/40",
    badgeText: "text-violet-700 dark:text-violet-300",
    badgeBorder: "border-violet-300 dark:border-violet-700",
    iconBg: "bg-violet-100 dark:bg-violet-900/40",
    iconText: "text-violet-600 dark:text-violet-400",
  },
  strength: {
    icon: Dumbbell,
    label: "Strength",
    accentBg: "bg-rose-500",
    accentBorder: "border-l-rose-500",
    badgeBg: "bg-rose-100 dark:bg-rose-900/40",
    badgeText: "text-rose-700 dark:text-rose-300",
    badgeBorder: "border-rose-300 dark:border-rose-700",
    iconBg: "bg-rose-100 dark:bg-rose-900/40",
    iconText: "text-rose-600 dark:text-rose-400",
  },
} as const;
